<?php

namespace CandidateBack\CommonBundle\Repository;

/**
 * CandidateCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidateCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
