<?php

namespace CandidateBack\CommonBundle\Repository;

/**
 * DiplomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomaRepository extends \Doctrine\ORM\EntityRepository
{
}
