<?php

namespace CandidateBack\CommonBundle\Repository;

/**
 * JobExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobExperienceRepository extends \Doctrine\ORM\EntityRepository
{
}
