<?php

namespace CandidateBack\CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CandidateBack\CommonBundle\Entity\Candidate;


/**
 * RealisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all realisations by desc date for a candidate
     * @param $candidate
     * @return array
     */
    public function getPublishedRealisationsForCandidateByDateDesc(Candidate $candidate)
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->select('r.id', 'r.title', 'r.date', 'r.description', 'r.isPublished')
            ->leftJoin('r.candidate', 'c')
            ->addSelect('c.id', 'c.createdAt', 'c.updatedAt', 'c.jobname', 'c.gender', 'c.firstname', 'c.lastname', 'c.email')
            ->where('r.isPublished = :isPublished')
            ->setParameter('isPublished', true)
            ->andWhere('r.candidate = :candidate')
            ->setParameter('candidate', $candidate)
            ->orderBy('r.date', 'DESC')
        ;

        return $qb->getQuery()->getArrayResult();
    }


}
